global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'aura-ingestor'
    static_configs:
      - targets: ['host.docker.internal:9091']

  - job_name: 'aura-query'
    static_configs:
      - targets: ['host.docker.internal:9092']

  - job_name: 'aura-router'
    static_configs:
      - targets: ['host.docker.internal:9093']

  - job_name: 'aura-storage'
    static_configs:
      - targets: ['host.docker.internal:9094']
